/** Generated by scripts/generate-pwa-splash.mjs — do not edit by hand. */

export const pwaSplashStartupImages: { url: string; media: string }[] = [
  {
    "url": "/splash/iphone-se-1.png",
    "media": "(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)"
  },
  {
    "url": "/splash/iphone-678-se.png",
    "media": "(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2)"
  },
  {
    "url": "/splash/iphone-678-plus.png",
    "media": "(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3)"
  },
  {
    "url": "/splash/iphone-x-xs-11pro.png",
    "media": "(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3)"
  },
  {
    "url": "/splash/iphone-xr-11.png",
    "media": "(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2)"
  },
  {
    "url": "/splash/iphone-xsmax-11promax.png",
    "media": "(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3)"
  },
  {
    "url": "/splash/iphone-12mini-13mini.png",
    "media": "(device-width: 360px) and (device-height: 780px) and (-webkit-device-pixel-ratio: 3)"
  },
  {
    "url": "/splash/iphone-12-13-14.png",
    "media": "(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3)"
  },
  {
    "url": "/splash/iphone-12promax-13promax-14plus.png",
    "media": "(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3)"
  },
  {
    "url": "/splash/iphone-14pro-15pro-16pro.png",
    "media": "(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3)"
  },
  {
    "url": "/splash/iphone-14promax-15plus.png",
    "media": "(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3)"
  }
];
